version: '3'

env:
  GOLANG_IMAGE: 'golang:1.22.5-bullseye'
  APP_BASE_IMAGE: 'alpine:3.18.6'
  POSTGRES_IMAGE: 'postgres:16.3-bullseye'
  ORY_KRATOS_IMAGE: 'oryd/kratos:v1.2.0'
  ORY_OATHKEEPER_IMAGE: 'oryd/oathkeeper:v0.40.7'


tasks:
  default:
    cmd: 'task --list-all'

  gen-sql:
    cmd: 'docker run --rm -v $(pwd):/src -w /src sqlc/sqlc:1.26.0 generate'

  run-env:
    env:
      COMPOSE_POSTGRES_ENABLE: '1'
      COMPOSE_ORY_ENABLE: '1'
    cmd: ./scripts/docker-compose.sh

  build:
    cmds:
      - go build -o ./bin/api ./cmd/api/main.go

  run-api:
    env:
      COMPOSE_POSTGRES_ENABLE: '1'
#      COMPOSE_ORY_ENABLE: '1'
      COMPOSE_API_ENABLE: '1'
    cmds:
      - ./scripts/docker-compose.sh