version: '3.9'

services:
  api:
    build:
      context: ./../../
      dockerfile: Dockerfile
      args:
        - GOLANG_IMAGE=${GOLANG_IMAGE}
        - APP_BASE_IMAGE=${APP_BASE_IMAGE}
    container_name: "api-${COMPOSE_PROJECT_NAME}"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - type: bind
        source: ./config.yaml
        target: /etc/config/api/config.yaml
    environment:
      - CONFIG_PATH=/etc/config/api/config.yaml
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
    command: "./api"
  swagger:
    image: swaggerapi/swagger-ui:v5.17.14
    container_name: "swagger-${COMPOSE_PROJECT_NAME}"
    ports:
      - "8089:8080"
    environment:
      - SWAGGER_JSON=/api/swagger.json
    volumes:
      - type: bind
        source: ./../../docs/swagger.json
        target: /api/swagger.json