logger:
  level: debug
  format: json
database:
  host: postgres-${COMPOSE_PROJECT_NAME}
  port: 5432
  user: postgres
  password: postgres
  database: langbridge
  log_tracing: true
http:
  port: 8080