version: '3.9'

services:
  postgres:
    image: postgres:16.3-bullseye
    restart: always
    shm_size: 128mb
    container_name: db-langbridge
    environment:
      PGUSER: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_MULTIPLE_DATABASES: langbridge,ory
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - langbridge-pg-data:/var/lib/postgresql/data
      - ./scripts/create-multiple-postgresql-databases.sh:/docker-entrypoint-initdb.d/create-multiple-postgresql-databases.sh
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 2s
      timeout: 1s
      retries: 7

volumes:
  langbridge-pg-data:
    driver: local
