services:
  kratos-migrate:
    image: oryd/kratos:v1.2.0
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DSN=postgres://postgres:postgres@db-langbridge:5432/ory?sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      - type: bind
        source: ./ory/config
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
  kratos:
    container_name: "kratos-langbridge"
    image: oryd/kratos:v1.2.0
    environment:
      - DSN=postgres://postgres:postgres@db-langbridge:5432/ory?sslmode=disable&max_conns=20&max_idle_conns=4
      - LOG_LEVEL=trace
    depends_on:
      - kratos-migrate
    ports:
      - '4433:4433' # public
      - '4434:4434' # admin
    restart: unless-stopped
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - type: bind
        source: ./ory/config
        target: /etc/config/kratos
  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - '4436:4436'
      - '4437:4437'

  # remove when we will have web ui
  kratos-selfservice-ui-node:
    image: oryd/kratos-selfservice-ui-node:v1.2.0
    ports:
      - "4455:4455"
    environment:
      - PORT=4455
      - SECURITY_MODE=
      - KRATOS_BROWSER_URL=http://127.0.0.1:4433/
      - COOKIE_SECRET=changeme
      - CSRF_COOKIE_NAME=ory_csrf_ui
      - CSRF_COOKIE_SECRET=changeme
      - KRATOS_PUBLIC_URL=http://kratos:4433/

    restart: on-failure
    depends_on:
      - kratos