basePath: /api/v1
definitions:
  internal_api_http_keys.Translate:
    properties:
      language:
        type: string
      value:
        type: string
    type: object
  key.Platform:
    enum:
    - WEB
    - IOS
    - ANDROID
    - OTHER
    type: string
    x-enum-varnames:
    - PlatformWeb
    - PlatformIOS
    - PlatformAndroid
    - PlatformOther
  keys.CreateKeyRequest:
    properties:
      existedTags:
        items:
          type: integer
        type: array
      name:
        type: string
      newTags:
        items:
          type: string
        type: array
      platforms:
        items:
          $ref: '#/definitions/key.Platform'
        type: array
      translates:
        items:
          $ref: '#/definitions/internal_api_http_keys.Translate'
        type: array
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Swagger Example API
  version: "1.0"
paths:
  /api/v1/projects/{projectID}/keys:
    post:
      consumes:
      - application/json
      parameters:
      - description: Project ID
        in: path
        name: projectID
        required: true
        type: integer
      - description: Create key request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/keys.CreateKeyRequest'
      produces:
      - application/json
      responses: {}
      summary: Create key with translates
      tags:
      - keys
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
